### ISSUE TITLE
Missing preprocessing tools and Jupyter notebooks

### ISSUE THREAD

**Issue by CooperColdwell** [c3lab/Apeiron#1]
I'm not sure how to start using the data, but the paper mentions code would be available to help with this. Can you provide any updates?

**Comment by Nunzio03** [comment]
Dear @CooperColdwell,
Thank you for your feedback. I'm Sorry but we didn't receive any notification from Github about this Issue, otherwise we would've fixed it earlier.

Many of the preprocessing steps are already done. In particular: the dataset is timestamped, labled (see CSV and .log files) and Aligned (event capture starts with zed2i capture).

With commit e425fc2 I've uploaded a readme with the folder description of a typical run (flight session), Docker files with all the instructions to build docker images to handle ZED2i and EVK4HD data and two jupyter notebooks + processing modules

Stay tuned for more data and let us know if you experience any other issue
